import type { EndpointRoleMapping } from "@/generated/prisma/client";
import { prisma } from "../libs/prisma";

export async function getEndpointRoleMappingsService(): Promise<EndpointRoleMapping[]> {
    return await prisma.endpointRoleMapping.findMany({
        orderBy: {
            createdAt: "desc",
        },
    });
}

export async function addEndpointRoleMapping(
    normalizedPath: string,
    allowedRole: string
): Promise<EndpointRoleMapping> {
    return await prisma.endpointRoleMapping.create({
        data: {
            normalizedPath,
            allowedRole,
            autoGenerated: false,
        },
    });
}

export async function removeEndpointRoleMapping(
    normalizedPath: string,
    allowedRole: string
): Promise<{ count: number }> {
    return await prisma.endpointRoleMapping.deleteMany({
        where: {
            normalizedPath,
            allowedRole,
        },
    });
}

export async function getDistinctRoles(): Promise<string[]> {
    const fromMappings = await prisma.endpointRoleMapping.findMany({
        distinct: ["allowedRole"],
        select: { allowedRole: true },
    });
    const fromRequestLogs = await prisma.requestLog.findMany({
        where: { role: { not: null } },
        distinct: ["role"],
        select: { role: true },
    });
    const roles = new Set<string>();
    fromMappings.forEach((m: { allowedRole: string }) => roles.add(m.allowedRole));
    fromRequestLogs.forEach((r: { role: string | null }) => {
        if (r.role) roles.add(r.role);
    });
    return Array.from(roles).sort();
}